{
    "name": "Purchase Demo",
    "version": "1.0.0",
    "summary": "Demo purchase workflow module",
    "author": "AutoGenerated",
    "category": "Purchases",
    "depends": ["base", "product"],
    "data": [
        "security/ir.model.access.csv",
        "views/purchase_views.xml",
    ],
    "installable": True,
    "application": True,
}
